image: niessan/omnetpp-inet:latest

stages:
    - build
    - test

before_script:
    - export NESTING=$(pwd)
    - export INET=/root/models/inet

build:
    stage: build
    script:
        - make INET=$INET makefiles
        - make INET=$INET MODE=debug -j$(grep -c proc /proc/cpuinfo)
	- make INET=$INET MODE=release -j$(grep -c proc /proc/cpuinfo)
        - test -f src/libnesting.so
	- test -f src/libnesting_dbg.so
    artifacts:
        paths:
            - src/libnesting.so
            - out/

test_release:
    stage: test
    script:
        - bash $NESTING/tests/test.sh
    artifacts:
        paths:
            - work

test_dbg:
    stage: test
    script:
        - MODE=debug bash $NESTING/tests/test.sh
    artifacts:
        paths:
            - work


