image: niessan/omnetpp-inet:latest

stages:
    - analysis
    - build
    - test

before_script:
    - export OMNETPP=/root/omnetpp
    - export NESTING=$(pwd)
    - export INET=/root/models/inet

build:
    stage: build
    script:
        - make INET=$INET makefiles
        - make INET=$INET MODE=debug -j$(grep -c proc /proc/cpuinfo)
        - make INET=$INET MODE=release -j$(grep -c proc /proc/cpuinfo)
        - test -f src/libnesting.so
        - test -f src/libnesting_dbg.so
    artifacts:
        paths:
            - src/libnesting.so
            - out/

test_release:
    stage: test
    script:
        - bash $NESTING/tests/run_tests.sh
    artifacts:
        paths:
            - work

test_dbg:
    stage: test
    script:
        - MODE=debug bash $NESTING/tests/run_tests.sh
    artifacts:
        paths:
            - work_dbg

code_quality:
    stage: analysis
    script:
        - python3 $NESTING/tests/run_cppcheck.py gl-code-quality-report.json
    artifacts:
        reports:
            codequality: gl-code-quality-report.json
        paths:
            - gl-code-quality-report.json
