image: docker:19.03.8
services:
    - docker:19.03.8-dind

stages:
    - build
    - test
    - release
    - deploy

variables:
    DOCKER_DRIVER: overlay
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
    stage: build
    script:
        - docker build --pull -t $CONTAINER_TEST_IMAGE .
        - docker push $CONTAINER_TEST_IMAGE

test_release:
    stage: test
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker run $CONTAINER_TEST_IMAGE /root/models/nesting/scripts/run_tests.sh

test_dbg:
    stage: test
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker run --env MODE=debug $CONTAINER_TEST_IMAGE /root/models/nesting/scripts/run_tests.sh

release-image:
    stage: release
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
        - docker push $CONTAINER_RELEASE_IMAGE
    only:
        - master
